# Generated by Django 5.0.7 on 2024-08-02 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('isAdmin', models.BooleanField(default=False)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('bio', models.CharField(default='', max_length=150)),
                ('dob', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(default='profile_images/defaultpfpsvg.png', upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('tagline', models.CharField(max_length=50, null=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='BusinessImages/')),
                ('image1', models.ImageField(upload_to='BusinessImages/')),
                ('image2', models.ImageField(upload_to='BusinessImages/')),
                ('image3', models.ImageField(upload_to='BusinessImages/')),
                ('image4', models.ImageField(upload_to='BusinessImages/')),
                ('image5', models.ImageField(upload_to='BusinessImages/')),
                ('phone_number', models.CharField(max_length=13)),
                ('website', models.URLField(null=True)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Automotive', 'Automotive'), ('Beauty', 'Beauty'), ('Hotel', 'Hotel'), ('Doctor', 'Doctor'), ('Restaurant', 'Restaurant'), ('Shopping', 'Shopping')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Automotive',
            fields=[
                ('business_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='two.business')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repair_services', models.BooleanField(default=False)),
                ('parts_sales', models.BooleanField(default=False)),
                ('towing_service', models.BooleanField(default=False)),
                ('car_wash', models.BooleanField(default=False)),
                ('appointment_required', models.BooleanField(default=False)),
            ],
            bases=('two.business',),
        ),
        migrations.CreateModel(
            name='BeautySpa',
            fields=[
                ('business_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='two.business')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('massage_services', models.BooleanField(default=False)),
                ('facial_treatments', models.BooleanField(default=False)),
                ('nail_services', models.BooleanField(default=False)),
                ('hair_styling', models.BooleanField(default=False)),
                ('makeup_services', models.BooleanField(default=False)),
                ('waxing', models.BooleanField(default=False)),
            ],
            bases=('two.business',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('business_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='two.business')),
                ('specialty', models.CharField(max_length=255)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accepts_insurance', models.BooleanField(default=False)),
                ('emergency_services', models.BooleanField(default=False)),
                ('appointment_required', models.BooleanField(default=False)),
            ],
            bases=('two.business',),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('business_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='two.business')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_service', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('spa', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
            ],
            bases=('two.business',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('business_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='two.business')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery', models.BooleanField(default=False)),
                ('take_out', models.BooleanField(default=False)),
                ('AirConditioning', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('pureVeg', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('smokingAllowed', models.BooleanField(default=False)),
            ],
            bases=('two.business',),
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('business_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='two.business')),
                ('clothing', models.BooleanField(default=False)),
                ('electronics', models.BooleanField(default=False)),
                ('groceries', models.BooleanField(default=False)),
                ('home_goods', models.BooleanField(default=False)),
                ('personal_care', models.BooleanField(default=False)),
                ('discounts_available', models.BooleanField(default=False)),
            ],
            bases=('two.business',),
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.CharField(max_length=15, null=True)),
                ('tue', models.CharField(max_length=15, null=True)),
                ('wed', models.CharField(max_length=15, null=True)),
                ('thu', models.CharField(max_length=15, null=True)),
                ('fri', models.CharField(max_length=15, null=True)),
                ('sat', models.CharField(max_length=15, null=True)),
                ('sun', models.CharField(max_length=15, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='two.business')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='two.categories'),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='two.business')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_data', models.CharField(choices=[('Google business profile, Whatsapp business account, Sub domain website', '99rs'), ('Google business profile, Whatsapp business account, Sub domain website, Current month festive post, Managing google business page', '99rspm'), ("Google business profile, Whatsapp business account, Sub domain website, Current month festive post, Managing google business page, Managing social media handle's, 2 marketing post for facebook instagram and google business page, 1 cover for facebook instagram and google business page", '999rs'), ("Google business profile, Whatsapp business account, Sub domain website, Current month festive post, Managing google business page, Managing social media handle's, 4 marketing post for facebook instagram and google business page, 1 cover for facebook instagram and google business page, 4 social media marketing post boast on facebook or instagram", '9,999rs'), ("Google business profile, Whatsapp business account, Sub domain website, Current month festive post, Managing google business page, Managing social media handle's, 4 marketing post for facebook instagram and google business page, 1 cover for facebook instagram and google business page, 4 social media marketing post boast on facebook or instagram, Website static website, Domain, Hosting, Website maintenance", '14,999rs'), ("Google business profile, Whatsapp business account, Sub domain website, Current month festive post, Managing google business page, Managing social media handle's, 4 marketing post for facebook instagram and google business page, 1 cover for facebook instagram and google business page, 4 social media marketing post boast on facebook or instagram, Website static website, Domain, Hosting, Website maintenance, Website static website, dynamic website, Ecom, Domain, Hosting, Website maintenance, 1 time 10 product listing(in case of ecom), Billing portal, Hrm portal, Inventory portal", '19,999rs')], max_length=600)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='two.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('twitter', models.CharField(max_length=100, null=True)),
                ('instagram', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('Video', models.FileField(upload_to='video/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dislikes', models.ManyToManyField(related_name='dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='two.video')),
            ],
        ),
    ]
