# Generated by Django 5.0.7 on 2024-07-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='forget_password_token',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
