# Generated by Django 5.0.7 on 2024-08-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
