# Generated by Django 5.0.7 on 2024-07-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0004_signup_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
    ]
