# Generated by Django 5.0.7 on 2024-07-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0009_remove_listing_email_listing_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-07-21 09:26:32.266416'),
            preserve_default=False,
        ),
    ]
