# Generated by Django 5.0.7 on 2024-07-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0010_listing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Automotive', 'Automotive'), ('Beauty', 'Beauty'), ('Hotels', 'Hotels'), ('Doctors', 'Doctors'), ('Restaurant', 'Restaurant'), ('Shopping', 'Shopping')], default='Automotive', max_length=50),
            preserve_default=False,
        ),
    ]
