# Generated by Django 5.0.7 on 2024-07-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0011_listing_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.IntegerField(choices=[(1, '99rs'), (2, '99rspm'), (3, '999rs'), (4, '9,999rs'), (5, '14,999rs'), (6, '19,999rs')])),
            ],
        ),
    ]
