# Generated by Django 5.0.7 on 2024-07-28 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0013_planprices_plan_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planprices',
            name='plan_id',
        ),
    ]
