# Generated by Django 5.0.7 on 2024-07-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0015_planprices_user_alter_planprices_plan_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rating',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
