# Generated by Django 5.0.7 on 2024-07-30 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0016_listing_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=50, null=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='BusinessLogos/')),
                ('images', models.ImageField(upload_to='BusinessImages/')),
                ('phone_number', models.CharField(max_length=13)),
                ('website', models.URLField()),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Automotive', 'Automotive'), ('Beauty', 'Beauty'), ('Hotel', 'Hotel'), ('Doctor', 'Doctor'), ('Restaurant', 'Restaurant'), ('Shopping', 'Shopping')], max_length=15),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('business_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='two.business')),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('delivery', models.BooleanField(default=False)),
                ('take_out', models.BooleanField(default=False)),
                ('AirConditioning', models.BooleanField(default=False)),
                ('petsAllowed', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('pureVeg', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('smokingAllowed', models.BooleanField(default=False)),
            ],
            bases=('two.business',),
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.CharField(max_length=15, null=True)),
                ('tue', models.CharField(max_length=15, null=True)),
                ('wed', models.CharField(max_length=15, null=True)),
                ('thu', models.CharField(max_length=15, null=True)),
                ('fri', models.CharField(max_length=15, null=True)),
                ('sat', models.CharField(max_length=15, null=True)),
                ('sun', models.CharField(max_length=15, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='two.business')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Automotive', 'Automotive'), ('Beauty', 'Beauty'), ('Hotel', 'Hotel'), ('Doctor', 'Doctor'), ('Restaurant', 'Restaurant'), ('Shopping', 'Shopping')], max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='two.categories'),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('twitter', models.CharField(max_length=100, null=True)),
                ('instagram', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
