# Generated by Django 5.0.7 on 2024-07-30 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0017_business_alter_listing_category_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automotive',
            fields=[
                ('business_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='two.business')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repair_services', models.BooleanField(default=False)),
                ('parts_sales', models.BooleanField(default=False)),
                ('towing_service', models.BooleanField(default=False)),
                ('car_wash', models.BooleanField(default=False)),
                ('appointment_required', models.BooleanField(default=False)),
            ],
            bases=('two.business',),
        ),
        migrations.CreateModel(
            name='BeautySpa',
            fields=[
                ('business_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='two.business')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('massage_services', models.BooleanField(default=False)),
                ('facial_treatments', models.BooleanField(default=False)),
                ('nail_services', models.BooleanField(default=False)),
                ('hair_styling', models.BooleanField(default=False)),
                ('makeup_services', models.BooleanField(default=False)),
                ('waxing', models.BooleanField(default=False)),
            ],
            bases=('two.business',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('business_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='two.business')),
                ('specialty', models.CharField(max_length=255)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accepts_insurance', models.BooleanField(default=False)),
                ('emergency_services', models.BooleanField(default=False)),
                ('appointment_required', models.BooleanField(default=False)),
            ],
            bases=('two.business',),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('business_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='two.business')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_service', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('spa', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
            ],
            bases=('two.business',),
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('business_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='two.business')),
                ('clothing', models.BooleanField(default=False)),
                ('electronics', models.BooleanField(default=False)),
                ('groceries', models.BooleanField(default=False)),
                ('home_goods', models.BooleanField(default=False)),
                ('personal_care', models.BooleanField(default=False)),
                ('discounts_available', models.BooleanField(default=False)),
            ],
            bases=('two.business',),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='max_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='min_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
