# Generated by Django 5.0.7 on 2024-07-30 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0020_business_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='automotive',
            name='user_automotive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='automotive', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beautyspa',
            name='user_beauty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='beautySpa', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='user_doc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='user_hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='user_res',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping',
            name='user_shopping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shopping', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
