# Generated by Django 5.0.7 on 2024-07-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0021_automotive_user_automotive_beautyspa_user_beauty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='rating',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
