# Generated by Django 5.0.7 on 2024-07-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0022_business_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='user',
        ),
    ]
