# Generated by Django 5.0.7 on 2024-07-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0023_remove_categories_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
