# Generated by Django 5.0.7 on 2024-07-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0024_alter_business_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='images',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='business',
            name='image2',
            field=models.ImageField(default=1, upload_to='BusinessImages/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='image3',
            field=models.ImageField(default=1, upload_to='BusinessImages/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='image4',
            field=models.ImageField(default=1, upload_to='BusinessImages/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='image5',
            field=models.ImageField(default=1, upload_to='BusinessImages/'),
            preserve_default=False,
        ),
    ]
