# Generated by Django 5.0.7 on 2024-07-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0025_rename_images_business_image1_business_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='BusinessImages/'),
            preserve_default=False,
        ),
    ]
