# Generated by Django 5.0.7 on 2024-07-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0027_remove_restaurant_petsallowed_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='country',
            field=models.CharField(default='India', max_length=100),
            preserve_default=False,
        ),
    ]
