# Generated by Django 5.0.7 on 2024-08-01 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0029_alter_signup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automotive',
            name='user_automotive',
        ),
        migrations.RemoveField(
            model_name='beautyspa',
            name='user_beauty',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user_doc',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='user_hotel',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='user_res',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='user_shopping',
        ),
    ]
