# Generated by Django 5.0.7 on 2024-08-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0030_remove_automotive_user_automotive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='logo',
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
