# Generated by Django 5.0.7 on 2024-08-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0031_remove_business_logo_alter_business_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/defaultpfpsvg.png', null=True, upload_to='profile_images/'),
        ),
    ]
