# Generated by Django 5.0.7 on 2024-08-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0032_alter_signup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='image',
            field=models.ImageField(default='profile_images/defaultpfpsvg.png', upload_to='profile_images/'),
        ),
    ]
